language: python

# this list can be easily generated py running `tox -l`
env:
    - TOX_ENV=py27-django18-sync
    - TOX_ENV=py27-django18-async
    - TOX_ENV=py27-django19-sync
    - TOX_ENV=py27-django19-async
    - TOX_ENV=py27-django110-sync
    - TOX_ENV=py27-django110-async

# Currently, Python 3.5 Interpreter is only available when it is specified
# in the travis python section. So we have to work around this with this include
# GitHub issue: https://github.com/travis-ci/travis-ci/issues/4794
matrix:
  include:
  - python: "3.6"
    env:
      - TOX_ENV=py36-django18-sync
  - python: "3.6"
    env:
      - TOX_ENV=py36-django18-async
  - python: "3.6"
    env:
      - TOX_ENV=py36-django19-sync
  - python: "3.6"
    env:
      - TOX_ENV=py36-django19-async
  - python: "3.6"
    env:
      - TOX_ENV=py36-django110-sync
  - python: "3.6"
    env:
      - TOX_ENV=py36-django110-async
  - python: "3.6"
    env:
      - TOX_ENV=py36-django20-sync
  - python: "3.6"
    env:
      - TOX_ENV=py36-django20-async

install:
    - pip install tox-travis
    - pip install coveralls

script:
    - tox -e $TOX_ENV

sudo: false

after_success:
    coveralls
